name: vps

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runner's shell
      - name: run vps
        run: curl -sSf https://sshx.io/get | sh -s run > sshx.txt

      - name: Save SSHX Link
        run: |
          grep -o 'https://sshx.io/s/.*' sshx.txt | head -n1 > link.txt

      - name: Sleep for 5.5 Hours
        run: sleep $((60 * 60 * 5 + 60 * 30))

      - name: Send Link to Discord
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1378973750665547826/9N8Sf-fMdYJcQkEYDD0fRoO9CNLookivifB55newp7r34q33_9_QdgQHvTNMJiJOwsKS
        run: |
          link=$(cat link.txt)
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"🔗 **New SSHX VPS is live!**\n$link\"}" \
               "$DISCORD_WEBHOOK"

      - name: Auto-Restart Workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/vps.yml/dispatches \
            -d '{"ref":"main"}'
