name: vps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run VPS and Save SSHX Link
        id: runvps
        run: |
          echo "Starting VPS setup..."
          curl -sSf https://sshx.io/get | sh -s run | tee sshx_output.log

          echo "Extracting SSHX link..."
          LINK=$(grep -o 'https://sshx.io/[a-zA-Z0-9]*' sshx_output.log | head -n 1)

          if [ -z "$LINK" ]; then
            echo "❌ SSHX link not found!"
            exit 1
          fi

          echo "✅ SSHX link found: $LINK"
          echo "sshx_link=$LINK" >> $GITHUB_OUTPUT
          echo "::notice::SSHX Link: $LINK"

      - name: Send SSHX link to Discord
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"🚀 VPS Started!\n🔗 SSHX Link: ${{ steps.runvps.outputs.sshx_link }}\"}" \
            https://discord.com/api/webhooks/1378973750665547826/9N8Sf-fMdYJcQkEYDD0fRoO9CNLookivifB55newp7r34q33_9_QdgQHvTNMJiJOwsKS

      - name: Sleep for 5.5 Hours
        run: |
          echo "Sleeping for 5.5 hours..."
          sleep $((60 * 60 * 5 + 60 * 30)) # 19800 seconds = 5.5 hours

      - name: Auto-Restart Workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔁 Restarting main.yml..."
          gh workflow run main.yml
